name: mesh_gradient
description: Render custom mesh gradients in realtime.
repository: https://github.com/benthillerkus/mesh_gradient
homepage: https://benthillerkus.github.io/mesh_gradient
issue_tracker: https://github.com/benthillerkus/mesh_gradient/issues
topics:
  - ui
  - widgets
  - shader
  - color
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  collection:
  flutter_color_models: ^1.3.3+2
  flutter_hooks: ^0.18.6
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  shaders:
    - "assets/shader.glsl"
    - "assets/oklch.glsl"
    - "assets/picker.glsl"
